"""
Django settings for restofast_project project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path
import dj_database_url

# Chemin principal du projet
BASE_DIR = Path(__file__).resolve().parent.parent


# =====================================================
# SECURITY SETTINGS
# =====================================================

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-bg*mq+qa*+_7qe3c!fvjly4&++ns+=02_4#9i$#3amn!=-j%tz')

# Passe automatiquement à False en production sur Render si la variable n'est pas définie à True
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Récupère l'étoile (*) configurée sur Render ou accepte le local par défaut
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost 127.0.0.1').split()


# =====================================================
# APPLICATIONS
# =====================================================

INSTALLED_APPS = [
    # Applications Django natives
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Application du projet
    'core',
]


# =====================================================
# MIDDLEWARE
# =====================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # Gestion des fichiers statiques en production (WhiteNoise)
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =====================================================
# URL / WSGI
# =====================================================

ROOT_URLCONF = 'restofast_project.urls'

WSGI_APPLICATION = 'restofast_project.wsgi.application'


# =====================================================
# TEMPLATES
# =====================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =====================================================
# DATABASE CONFIGURATION (LOCAL & PRODUCTION)
# =====================================================

# dj-database-url va lire automatiquement la variable DATABASE_URL de Render.
# Si elle n'existe pas (en local), il se rabattra sur votre PostgreSQL local.
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get(
            'DATABASE_URL',
            'postgres://postgres:0000@localhost:5432/universite_db'
        )
    )
}


# =====================================================
# VALIDATION MOT DE PASSE
# =====================================================

AUTH_PASSWORD_VALIDATORS = []


# =====================================================
# INTERNATIONALISATION
# =====================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =====================================================
# STATIC FILES
# =====================================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# =====================================================
# AUTHENTIFICATION
# =====================================================

LOGIN_URL = 'connexion_unique'

LOGIN_REDIRECT_URL = 'connexion_unique'

LOGOUT_REDIRECT_URL = 'connexion_unique'
