# Generated by Django 6.0.3 on 2026-07-17 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_numero', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('SERVI', 'Servi'), ('PAYE', 'Payé & Clôturé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('moyen_paiement', models.CharField(blank=True, choices=[('ESPECE', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte Bancaire')], max_length=20, null=True)),
                ('montant_recu', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('caissier', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Caissier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_encaissees', to=settings.AUTH_USER_MODEL)),
                ('serveur', models.ForeignKey(limit_choices_to={'groups__name': 'Serveur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_prises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuel', models.PositiveIntegerField(default=0)),
                ('stock_alerte', models.PositiveIntegerField(default=5, help_text="Seuil pour déclencher l'alerte rupture")),
                ('disponible', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='core.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text="Prix au moment de l'achat", max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produit')),
            ],
        ),
    ]
