# Generated by Django 6.0.3 on 2026-07-17 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_commande_table_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='lignecommande',
            options={'verbose_name': 'Ligne de commande', 'verbose_name_plural': 'Lignes de commande'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='table_reference',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='montant_recu',
            new_name='total_montant',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='moyen_paiement',
        ),
        migrations.AddField(
            model_name='commande',
            name='traiteur',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Traiteur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_preparees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='est_pret',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('PRET', 'Prêt'), ('PAYEE', 'Payée'), ('ANNULE', 'Annulée')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_alerte',
            field=models.PositiveIntegerField(default=5, help_text='Seuil de stock critique'),
        ),
        migrations.CreateModel(
            name='ReservationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='core.produit')),
                ('serveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation de stock',
                'verbose_name_plural': 'Réservations de stock',
                'unique_together': {('produit', 'session_key')},
            },
        ),
        migrations.DeleteModel(
            name='StockReservation',
        ),
    ]
