# Generated by Django 6.0.7 on 2026-07-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_commande_options_alter_lignecommande_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='commande',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lignecommande',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reservationstock',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='reservationstock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='commande',
            name='traiteur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_actuel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_alerte',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='reservationstock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit'),
        ),
        migrations.AlterField(
            model_name='reservationstock',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservationstock',
            name='session_key',
            field=models.CharField(max_length=100),
        ),
    ]
